{% set version = "1.0-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deldir
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deldir_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deldir/deldir_{{ version }}.tar.gz
  sha256: 6df6d8325c607e0b7d63cbc53c29e774eff95ad4acf9c7ec8f70693b0505f8c5

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('deldir')"           # [not win]
    - "\"%R%\" -e \"library('deldir')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=deldir
  license: GPL-2.0-or-later
  summary: Calculates the Delaunay triangulation and the Dirichlet or Voronoi tessellation (with respect to the entire plane) of a planar point set. Plots triangulations and tessellations in various ways.  Clips tessellations to sub-windows. Calculates perimeters of tessellations.  Summarises information about the tiles
    of the tessellation.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: deldir
# Version: 0.1-23
# Date: 2019-07-31
# Title: Delaunay Triangulation and Dirichlet (Voronoi) Tessellation
# Author: Rolf Turner
# Maintainer: Rolf Turner <r.turner@auckland.ac.nz>
# Depends: R (>= 0.99)
# Suggests: polyclip
# Imports: graphics, grDevices
# Description: Calculates the Delaunay triangulation and the Dirichlet or Voronoi tessellation (with respect to the entire plane) of a planar point set. Plots triangulations and tessellations in various ways.  Clips tessellations to sub-windows. Calculates perimeters of tessellations.  Summarises information about the tiles of the tessellation.
# LazyData: true
# ByteCompile: true
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-07-31 02:06:08 UTC; rolf
# Repository: CRAN
# Date/Publication: 2019-07-31 05:00:09 UTC
