{% set version = '0.1-22' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deldir
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deldir_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deldir/deldir_{{ version }}.tar.gz
  sha256: f07204d7095c2c56288a7de91990b88424c3d1a0d6464296ffd93dbea8655919

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('deldir')"           # [not win]
    - "\"%R%\" -e \"library('deldir')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=deldir
  license: GPL (>= 2)
  summary: Calculates the Delaunay triangulation and the Dirichlet or Voronoi tessellation (with
    respect to the entire plane) of a planar point set. Plots triangulations and tessellations
    in various ways.  Clips tessellations to sub-windows. Calculates perimeters of tessellations.  Summarises
    information about the tiles of the tessellation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: deldir
# Version: 0.1-22
# Date: 2019-07-05
# Title: Delaunay Triangulation and Dirichlet (Voronoi) Tessellation
# Author: Rolf Turner
# Maintainer: Rolf Turner <r.turner@auckland.ac.nz>
# Depends: R (>= 0.99)
# Suggests: polyclip
# Imports: graphics, grDevices
# Description: Calculates the Delaunay triangulation and the Dirichlet or Voronoi tessellation (with respect to the entire plane) of a planar point set. Plots triangulations and tessellations in various ways.  Clips tessellations to sub-windows. Calculates perimeters of tessellations.  Summarises information about the tiles of the tessellation.
# LazyData: true
# ByteCompile: true
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-07-05 03:05:47 UTC; rolf
# Repository: CRAN
# Date/Publication: 2019-07-05 04:30:14 UTC
