travis:
  secure:
    BINSTAR_TOKEN: LmKiEvd6xsHpUKHycuZcMxrcAvrhFI+hyAbzxRPyc3uvhKONxF/aS/sURFVlN/0dQuUUb7UmB5aiNmGqKQeqkjnfjwLwi+pPewdkvr9YrakfwBSvnlkfw2q1yhDP6woOxcCJMKWqZgL5DgQ22TAnKQBQdTZveMk89gCKBgzVBYO78LR7PmlyWEd27K3c8rfYqbxqCBgWlY9VDm2wbjVt0xloA266w77CapgMOiGmGsK+4QSjVggRhSQPVnP/pPsWXcxdAym77FEWAXh3o2n5sU3p8bTDUuCn7KAtWbZ1Mi9jsOb4BfJCR1bZGNGpX7Y5w77wvh2LFVR1qE1YhemVkPPqDyHVNbjkOQXf2FOQXDXGIDedrKT+C0iJx6mcbCxLyO1xDVE4lyjAXHkuRNFAXeUM023ygJGU5UWyp/Za4fDCpp0NLNbiHTFCgAWouGJXdkJOkWkTp1kJevnY0sv50xyRUm8hVUXhn47A6VEqyWphbmum+B6GV3lhU2c4SiJPCxu6sdSNyfm8R5sonWvDYRDeIv0o6oyDW/vsn+04fu24HS4W8AUwHJ59ICO4pJcnBmb8YsEw3vFfMtLaRc2i9wDK5yex5bMCdcq1vEwlvq4eeaiXuYfCs3+noRaKJZdHkE2PmwJzW/Ywnd6ru0B72ScLTG3vL2+Mfq/hYSJwYWE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
